USE DBlivraria2sem2021;

/*PAGAMENTO*/
INSERT INTO PAGAMENTO (DESCRICAO_PAG) VALUES ('DEBITO');
INSERT INTO PAGAMENTO (DESCRICAO_PAG) VALUES ('BOLETO');
INSERT INTO PAGAMENTO (DESCRICAO_PAG) VALUES ('CRED A VISTA');
INSERT INTO PAGAMENTO (DESCRICAO_PAG) VALUES ('PARC 2 VEZES SEM JUROS');
INSERT INTO PAGAMENTO (DESCRICAO_PAG) VALUES ('PARC 3 VEZES SEM JUROS');
INSERT INTO PAGAMENTO (DESCRICAO_PAG) VALUES ('PARC 4 VEZES SEM JUROS');
INSERT INTO PAGAMENTO (DESCRICAO_PAG) VALUES ('PARC 5 VEZES SEM JUROS');
INSERT INTO PAGAMENTO (DESCRICAO_PAG) VALUES ('PARC 6 VEZES COM JUROS');
INSERT INTO PAGAMENTO (DESCRICAO_PAG) VALUES ('PARC 7 VEZES COM JUROS');
INSERT INTO PAGAMENTO (DESCRICAO_PAG) VALUES ('PARC 8 VEZES COM JUROS');
INSERT INTO PAGAMENTO (DESCRICAO_PAG) VALUES ('PARC 9 VEZES COM JUROS');
INSERT INTO PAGAMENTO (DESCRICAO_PAG) VALUES ('PARC 10 VEZES COM JUROS');
 
/*ESTADO*/
INSERT INTO ESTADO VALUES ('AC', 'ACRE');
INSERT INTO ESTADO VALUES ('AL', 'ALAGOAS');
INSERT INTO ESTADO VALUES ('AP', 'AMAPÁ');
INSERT INTO ESTADO VALUES ('AM', 'AMAZONAS');
INSERT INTO ESTADO VALUES ('BA', 'BAHIA');
INSERT INTO ESTADO VALUES ('CE', 'CEARÁ');
INSERT INTO ESTADO VALUES ('DF', 'DISTRITO FEDERAL');
INSERT INTO ESTADO VALUES ('ES', 'ESPÍRITO SANTO');
INSERT INTO ESTADO VALUES ('GO', 'GOIÁS');
INSERT INTO ESTADO VALUES ('MA', 'MARANHÃO');
INSERT INTO ESTADO VALUES ('MT', 'MATO GROSSO');
INSERT INTO ESTADO VALUES ('MS', 'MATO GROSSO DO SUL');
INSERT INTO ESTADO VALUES ('MG', 'MINAS GERAIS');
INSERT INTO ESTADO VALUES ('PA', 'PARÁ');
INSERT INTO ESTADO VALUES ('PB', 'PARAÍBA');
INSERT INTO ESTADO VALUES ('PR', 'PARANÁ');
INSERT INTO ESTADO VALUES ('PE', 'PERNAMBUCO');
INSERT INTO ESTADO VALUES  ('PI', 'PIAUÍ');
INSERT INTO ESTADO VALUES ('RJ', 'RIO DE JANEIRO');
INSERT INTO ESTADO VALUES ('RN', 'RIO GRANDE DO NORTE');
INSERT INTO ESTADO VALUES ('RS', 'RIO GRANDE DO SUL');
INSERT INTO ESTADO VALUES ('RO', 'RONDÔNIA');
INSERT INTO ESTADO VALUES ('RR', 'RORAIMA');
INSERT INTO ESTADO VALUES ('SC', 'SANTA CATARINA');
INSERT INTO ESTADO VALUES ('SP', 'SÃO PAULO');
INSERT INTO ESTADO VALUES ('SE', 'SERGIPE');
INSERT INTO ESTADO VALUES ('TO', 'TOCANTINS');

/*FORMATO_LIVRO*/
INSERT INTO FORMATO_LIVRO (descricao_for) VALUES ('CAPA DURA');
INSERT INTO FORMATO_LIVRO (descricao_for) VALUES ('GRAMPO');
INSERT INTO FORMATO_LIVRO (descricao_for) VALUES ('BROCHURA');
INSERT INTO FORMATO_LIVRO (descricao_for) VALUES ('DIGITAL');
INSERT INTO FORMATO_LIVRO (descricao_for)VALUES ('ASPIRAL');



 /*CATEGORIA*/
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('ADMINISTRAÇÃO');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('ARTES');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('AUTOAJUDA');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('CIÊNCIAS BIOLÓGICAS');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('CIÊNCIAS EXATAS');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('CIÊNCIAS HUMANAS E SOCIAIS');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('DIDÁTICOS');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('DIREITO');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('DIVERSOS');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('ECONOMIA');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('ESOTERISMO');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('ESPORTES E LAZER');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('GEOGRAFIA E HISTORIA');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('INFORMÁTICA');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('LINGUÍSTICA');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('LITERATURA BRASILEIRA	');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('LITERATURA ESTRANGEIRA');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('MEDICINA');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('PSICOLOGIA E PSICANÁLISE');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('RELIGIÃO');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('FICÇÃO CIENTÍFICA FANTASIA');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('BIOGRAFIA');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('AVENTURA');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('FANTASIA');
INSERT INTO CATEGORIA(DESCRICAO_CAT) VALUES ('INFANTO JUVENIL');


/* EDITORA */
INSERT INTO EDITORA(NOME_ED) VALUES ('INTRINSECA');
INSERT INTO EDITORA(NOME_ED) VALUES ('ARQUEIRO');
INSERT INTO EDITORA(NOME_ED) VALUES ('RECORD');
INSERT  INTO EDITORA(NOME_ED) VALUES ('SEXTANTE / GMT');
INSERT INTO EDITORA(NOME_ED) VALUES ('GENTE');
INSERT INTO EDITORA(NOME_ED) VALUES ('EDITORA NACIONAL');
INSERT INTO EDITORA(NOME_ED) VALUES ('CAMINHO SUAVE ED.');
INSERT INTO EDITORA(NOME_ED) VALUES ('ROCCO');
INSERT INTO EDITORA(NOME_ED) VALUES ('AGORA EDITORA');
INSERT INTO EDITORA(NOME_ED) VALUES ('COMPANHIA DAS LETRAS');
INSERT INTO EDITORA(NOME_ED) VALUES ('OBJETIVA');
INSERT INTO EDITORA(NOME_ED) VALUES ('BUZZ EDITORA');
INSERT INTO EDITORA(NOME_ED) VALUES ('RECORD');
INSERT INTO EDITORA(NOME_ED) VALUES ('GLOBO ART');
INSERT INTO EDITORA(NOME_ED) VALUES ('ALPH');
INSERT INTO EDITORA(NOME_ED) VALUES ('VALENTINA');
INSERT INTO EDITORA(NOME_ED) VALUES ('ARTMED'); 
INSERT INTO EDITORA(NOME_ED) VALUES ('FARO EDITORIAL');
INSERT INTO EDITORA(NOME_ED) VALUES ('BALÃO EDITORIAL');
INSERT INTO EDITORA(NOME_ED) VALUES ('BERTRAND BRASIL');
INSERT INTO EDITORA(NOME_ED) VALUES ('DAVID FINKING BOOKS');
INSERT INTO EDITORA(NOME_ED) VALUES ('SARAIVA');
INSERT INTO EDITORA(NOME_ED) VALUES ('MARTINS FONTES');

/*FUNCIONARIO*/
INSERT INTO FUNCIONARIO VALUES ('JOÃO ALMEIDA');
INSERT INTO FUNCIONARIO VALUES ('MARIA DE OLIVEIRA');
INSERT INTO FUNCIONARIO VALUES ('CARLOS DA SILVA');
INSERT INTO FUNCIONARIO VALUES ('ANA DA CRUZ');
INSERT INTO FUNCIONARIO VALUES ('JOSE DA COSTA');

